name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out source"
      uses: actions/checkout@v2
    - name: "Install dependencies"
      run: "pip install .[dev]"
    - name: "lint.sh"
      run: "./scripts/lint.sh"
    - name: "git diff"
      run: "git diff --exit-code"

  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out source"
      uses: actions/checkout@v2
    - name: "Install dependencies"
      run: "pip install .[test]"
    - name: "test.sh"
      run: "./scripts/test.sh"
